version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: stformat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

dockers_v2:
  - id: stformat
    dockerfile: Dockerfile
    images:
      - "ghcr.io/ysmilda/stformat"
    tags:
      - "{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    disable: '{{ .IsSnapshot }}'
    annotations:
      "org.opencontainers.image.description": "An opinionated formatter for IEC 61131-3 Structured Text (ST) and TwinCAT XML project files."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "MIT"

winget:
  - name: stformat
    publisher: Ysmilda
    publisher_url: https://github.com/ysmilda
    publisher_support_url: https://github.com/ysmilda/stformat/issues
    homepage: https://github.com/ysmilda/stformat
    license: "MIT"
    short_description: "An opinionated formatter for IEC 61131-3 Structured Text (ST) and TwinCAT XML project files."
    tags:
      - formatter
      - structured-text
      - twincat
      - plc
    skip_upload: auto
    repository:
      owner: ysmilda
      name: winget-pkgs
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"
      branch: "{{ .ProjectName }}-{{ .Version }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@users.noreply.github.com

homebrew_casks:
  - name: stformat
    binaries:
      - stformat
    homepage: https://github.com/ysmilda/stformat
    description: "An opinionated formatter for IEC 61131-3 Structured Text (ST) and TwinCAT XML project files."
    skip_upload: auto
    repository:
      owner: ysmilda
      name: homebrew-tap
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"
      branch: main
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@users.noreply.github.com

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
