// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace format
{
    internal sealed partial class Vsix
    {
        public const string Id = "format.71bd2de1-f667-4433-bffb-b02255179322";
        public const string Name = "StFormat";
        public const string Description = @"Formatter for ST/TwinCat";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Yorick Smilda (Viventris)";
        public const string Tags = "";
    }
}
